### ISSUE TITLE
Watch tower

### ISSUE THREAD

**Issue by Thienanbad** [shannaurelle/Extra-Buildings#1]
Why watch tower unbuildable?

**Comment by shannaurelle** [comment]
Watch tower is not in the list of buildings yet. Do you like to add it here?

**Comment by Thienanbad** [comment]
No please, it will get more difficult to take a city

Vào 6:28, Th 7, 16 thg 4, 2022 Shann Aurelle Ripalda <
***@***.***> đã viết:

**Comment by shannaurelle** [comment]
Okay, I will not make it :>

**Comment by Thienanbad** [comment]
Thank you very much. Love your mod.

Vào 15:48, Th 7, 16 thg 4, 2022 Shann Aurelle Ripalda <
***@***.***> đã viết:
