### ISSUE TITLE
Mod-checker Error: Under G&K Ruleset

### ISSUE THREAD

**Issue by Kuldebar** [shannaurelle/Extra-Buildings#14]
Apothecary's unique "All newly-trained [Melee] units [in this city] receive the [Organic Remedies] promotion" contains parameter Organic Remedies, which does not fit parameter type promotion !

**Comment by shannaurelle** [comment]
Thanks for letting me know :> If I can't seem to fix it I may have to remove this promotion on the next update

**Comment by shannaurelle** [comment]
Issue fixed. Thanks for reporting :>
