### ISSUE TITLE
Add Simplified Chinese translation

### ISSUE THREAD

**Issue by Jack1588** [shannaurelle/Extra-Buildings#21]
I would like to help translate for the convenience of Chinese speaker players

**Comment by shannaurelle** [comment]
You can send me a PR if you want to contribute

**Comment by Jack1588** [comment]
> You can send me a PR if you want to contribute

Regarding the previous translation request, I have now completed the translation. If possible, please see the pull request. Thank you.

**Comment by shannaurelle** [comment]
Seen and merged.
