### ISSUE TITLE
The buildings are kinda OP

### ISSUE THREAD

**Issue by HeLLoTheRe217** [shannaurelle/Extra-Buildings#3]
The buildings are good but too good, I think there's too much bonuses per buildings and there's not even a maintenance cost on them which makes it op for a small sacrifice. Hopefully you update it thank you.

**Comment by shannaurelle** [comment]
Thank you so much for this review! I will think of a great scheme in adding some "maintenance" for these buildings. I will inform my updates here once they are done :>
