### ISSUE TITLE
No icon used for Warehouses

### ISSUE THREAD

**Issue by NielsCW** [shannaurelle/Extra-Buildings#30]
The default building icon is used for the Warehouses building instead of the icon provided by the mod (see image).

It appears that `Warehouses` is used in [Buildings.json](https://github.com/shannaurelle/Extra-Buildings/blob/a6e54c8b4413e581155feb7989765e9ceb961486/jsons/Buildings.json#L237), whereas `Warehouse` is used in [Images](https://github.com/shannaurelle/Extra-Buildings/blob/409cc232e63a1db6c131af3c5f4b89568a662c80/Images/BuildingIcons/Warehouse.png).

I suggest to rename the image because renaming the building affects translations

![Screenshot_20240922-090007](https://github.com/user-attachments/assets/c3c082e7-f0fc-4552-8970-28ff333ef48f)

**Comment by shannaurelle** [comment]
Committed PR and merged.
