### ISSUE TITLE
Smokery still shown under buildings despite Slaughterhouse requirement not met

### ISSUE THREAD

**Issue by NielsCW** [shannaurelle/Extra-Buildings#31]
Slaughterhouse requires worked sheep, deer, cattle or horses near the city.

I suggest letting Smokery also require this. Other buildings that depend on a building also copy its city requirements (e.g. Seaport requires being next to coast just like its required building (Harbor) does).

![Screenshot_20240922-085929](https://github.com/user-attachments/assets/095b6b74-b34b-4301-b49e-2ac76972e82f)

**Comment by shannaurelle** [comment]
Committed PR and merged.
